version: "3.8"

services:
  xdp-app:
    container_name: xdp-app
    image: xdp-app
    privileged: true
    network_mode: host
    volumes:
      - /usr/lib/debug/boot/vmlinux-6.8.0-64-generic:/sys/kernel/btf/vmlinux:ro
    stdin_open: true
    tty: true
